project:
  type: website

website:
  title: "My Website"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: project
        href: project.qmd
      - text: softball
        href: softball.qmd
